Forum/Forum.Web/Controllers/Admin/AdminController.cs
using Forum.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Web.Controllers.Admin
{
    public class AdminController : Controller
    {
        private readonly IUserService userService;
        public AdminController(IUserService userService)
        {
            this.userService = userService;
        }
        public IActionResult Index()
        {
            var users = this.userService.GetAll();
            return View(users);
        }
        public IActionResult BlockUser(string email)
        {
            try
            {
                var user = this.userService.GetByEmail(email);
                this.userService.BlockUser(user.UserId, true);
            }
            catch (Exception)
            {

                throw;
            }
            return this.RedirectToAction("Index"); ;
        }
        public IActionResult UnblockUser(string email)
        {
            try
            {
                var user = this.userService.GetByEmail(email);
                this.userService.BlockUser(user.UserId, false);
            }
            catch (Exception)
            {

                throw;
            }
            return this.RedirectToAction("Index"); ;
        }
    }
}

Forum/Forum.Web/Controllers/Posts/MyPostsController.cs
using Forum.Models;
using Forum.Services.Contracts;
using Forum.Services.Exceptions;
using Forum.Services.PostService;
using Forum.Web.Controllers.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Web.Controllers.Posts
{
    public class MyPostsController : BaseController
    {
        private readonly IPostService postService;
        private readonly ICategoryService categoryService;

        public MyPostsController(IPostService postService, IUserService userService, ICategoryService categoryService)
            : base(userService)
        {
            this.postService = postService;
            this.categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var myPosts = this.postService.GetAllByUser(CurrentUser.UserId);
            return View(myPosts);
        }

        public IActionResult Create()
        {
            var post = new PostCreateViewModel();
            return this.PostView(post);
        }

        [HttpPost]
        public IActionResult Create(PostCreateViewModel post)
        {

            post.UserId = CurrentUser.UserId;
            post.Categories = this.GetCategories();

            if (!this.ModelState.IsValid)
            {
                return this.View(post);
            }

            this.postService.Create(post);
            return this.RedirectToAction("Index","Posts");
            
        }
        public IActionResult Edit(int id)
        {
            var post = this.postService.GetByIdModel(id);
            return this.PostView(post.ToViewModel());
        }
        [HttpPost]
        public IActionResult Edit (int id, PostCreateViewModel post)
        {
            if (!this.ModelState.IsValid)
            {
                return this.PostView(post);
            }
            try
            {      
                this.postService.Update(id, post);
            }
            catch (EntityNotFoundException)
            {
                return this.View(PostNotFound(id));
            }
            return this.RedirectToAction(nameof(this.Index));
        }
        private IActionResult PostView(PostCreateViewModel postViewModel)
        {
            postViewModel.Categories = this.GetCategories();
            return this.View(postViewModel);
        }

            private SelectList GetCategories()
        {
            var categories = this.categoryService.GetAll();
            return new SelectList(categories,"CategoryId","Name");
        }
        private IActionResult PostNotFound(int id)
        {
            this.Response.StatusCode = StatusCodes.Status404NotFound;
            this.ViewData["error"] = $"Post with id {id} does not exist.";
            return this.View("Error");
        }
    }
}

Forum/Forum.Web/Controllers/Posts/PostsController.cs
using Forum.Models;
using Forum.Services.Contracts;
using Forum.Services.PostService;
using Forum.Web.Controllers.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Web.Controllers
{
    public class PostsController : BaseController
    {
        private readonly IPostService postService;
        private readonly IPostLikeService postLikeService;
        private readonly ICommentLikeService commentLikeService;


        public PostsController(IPostService postService, IUserService userService, IPostLikeService postLikeService, ICommentLikeService commentLikeService)
       : base(userService)
        {
            this.postService = postService;
            this.postLikeService = postLikeService;
            this.commentLikeService = commentLikeService;
        }

        public IActionResult Index()
        {
            var posts = this.postService.GetAllPosts();
            return View(posts);
        }

        public IActionResult CommentsForPost(int id)
        {
            var post = this.postService.GetById(id);
            ViewBag.postId = id;

            return View(post);
        }

        public IActionResult LikesForPost(int id)
        {
            var likeModel = new PostLikeCreateModel
            {
                PostId = id,
                UserId = this.CurrentUser.UserId
            };

            this.postLikeService.Create(likeModel);

            return this.RedirectToAction("Index");
        }

       public IActionResult LikesForComment(int id)
       {
           var likeModel = new CommentLikeCreateModel();
           likeModel.CommentId = id;
           likeModel.UserId = CurrentUser.UserId;
           this.commentLikeService.Create(likeModel);
           return this.RedirectToAction("CommentsForPost", new { id = id });
       }
               
       public IActionResult AddCommentForPost(int postId, string description)
       {
           var commentModel = new CommentCreateModel();
           commentModel.PostId = postId;
           commentModel.UserId = CurrentUser.UserId;
           commentModel.Description = description;
           return this.RedirectToAction("CommentsForPost", new { id = postId });
       }
    }
}

Forum/Forum.Web/Controllers/Profile/ProfileController.cs
using Forum.Models;
using Forum.Services.Contracts;
using Forum.Web.Controllers.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Web.Controllers.Profile
{
    public class ProfileController : BaseController
    {
        public ProfileController(IUserService userService)
            : base(userService)
        {

        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UploadImage()
        {
            var file = Request.Form.Files[0];

            var img = new ImageModel();
            img.ImageTitle = file.FileName;
            img.User = CurrentUser;

            MemoryStream ms = new MemoryStream();
            file.CopyTo(ms);
            img.ImageData = ms.ToArray();

            ms.Close();
            ms.Dispose();

            this.userService.UploadPicture(img);

            ViewBag.Message = "Image(s) stored in database!";

            return View("Index");
        }

        [HttpPost]
        public ActionResult RetrieveImage()
        {
            var img = this.userService.GetPicture(CurrentUser.UserId);
            
            string imageBase64Data = Convert.ToBase64String(img.ImageData);
            string imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);

            ViewBag.ImageTitle = img.ImageTitle;
            ViewBag.ImageDataUrl = imageDataURL;

            return View("Index");
        }
    }
}

Forum/Forum.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["CurrentUser"] = this.Context.Session.Get("CurrentUser");
    this.ViewData["CurrentRoles"] = this.Context.Session.GetString("CurrentRoles");
}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Forum</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

</head>
<body>
    <div class="box">
        <div class="header">
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <div class="container-fluid">
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">Forum</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarcolor01" aria-controls="navbarcolor01" aria-expanded="false" aria-label="toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarcolor01">
                        <ul class="navbar-nav me-auto">
                            @if (!(bool)this.ViewData["isAuthenticated"])
                            {
                                @*<li class="nav-item">
                <a asp-controller="About" asp-action="Index" class="nav-link">About</a>
            </li>*@
                            }
                            else
                            {
                                if (this.ViewData["CurrentRoles"].ToString() == "user")
                                {
                                    <li class="nav-item">
                                        <a asp-controller="Posts" asp-action="Index" class="nav-link">Posts</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="MyPosts" asp-action="Create" class="nav-link">New post</a>
                                    </li>
                                }
                                if (this.ViewData["CurrentRoles"].ToString() == "admin")
                                {
                                    <li class="nav-item">
                                        <a asp-controller="Admin" asp-action="Index" class="nav-link">Users</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="Posts" asp-action="Index" class="nav-link">Posts</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="MyPosts" asp-action="Create" class="nav-link">New post</a>
                                    </li>
                                }
                            }
                        </ul>
                        <h4>
                            @if (!(bool)this.ViewData["isAuthenticated"])
                            {
                                <a asp-controller="Auth" asp-action="Register" class="btn btn-secondary">Sign Up</a>
                                <a asp-controller="Auth" asp-action="Login" class="btn btn-secondary">Sign In</a>
                            }
                            else
                            {
                                if (this.ViewData["CurrentRoles"].ToString() == "user")
                                {
                                    <a asp-controller="MyPosts" asp-action="Index" class="btn btn-secondary">My Posts</a>
                                }
                                <a asp-controller="Profile" asp-action="Index" class="btn btn-secondary">Settings</a>
                                <a asp-controller="Auth" asp-action="Logout" class="btn btn-secondary">Sign Out</a>
                            }
                        </h4>
                    </div>
                </div>
            </nav>
        </div>

        <div class="content bgi" style="margin-top: 10px; background-image: url('/img/DelverITGlobal.png');">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        @*<footer>
            <div class="border-top footer bg-primary">
                    &copy; 2021 - Forum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    </div>
    <script src="lib/bootstrap/dist/js/bootstrap.js"></script>
</body>
</html>