Forum/Forum.Web/Controllers/Comments/CommentsController.cs
using Forum.Models;
using Forum.Services.Contracts;
using Forum.Services.PostService;
using Forum.Web.Controllers.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Web.Controllers.Comments
{
    public class CommentsController : BaseController
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly ICommentService commentService;
        private readonly ICommentLikeService commentLikeService;

        public CommentsController(IPostService postService, IUserService userService, ICommentService commentService,ICommentLikeService commentLikeService)
            : base(userService)
        {
            this.postService = postService;
            this.commentService = commentService;
            this.commentLikeService = commentLikeService;
        }

        public IActionResult Index(int postId)
        {
            ViewBag.postId = postId;

            return View("Index");
        }

        [HttpPost]
        public IActionResult CreateCommentForPost([FromForm] int postId, string description)
        {
            //var userName = this.HttpContext.Session.GetString("CurrentUser");
            //var user = this.userService.GetByEmail(userName);
            var commentCreateModel = new CommentCreateModel();
            commentCreateModel.PostId = postId;
            commentCreateModel.UserId = CurrentUser.UserId;
            commentCreateModel.Description = description;
            this.commentService.Create(commentCreateModel);

            return RedirectToAction("CommentsForPost", "Posts", new { id = postId });
        }

        public IActionResult LikesForComment(int postId, int id)
        {
            //var userName = this.HttpContext.Session.GetString("CurrentUser");
            //var user = this.userService.GetByEmail(userName);
            var likeModel = new CommentLikeCreateModel();
            likeModel.CommentId = id;
            likeModel.UserId = CurrentUser.UserId;
            this.commentLikeService.Create(likeModel);

            return this.RedirectToAction("CommentsForPost","Posts", new { id = postId });
        }        
    }
}

Forum/Forum.Web/Controllers/Posts/MyPostsController.cs
using Forum.Models;
using Forum.Services.Contracts;
using Forum.Services.Exceptions;
using Forum.Services.PostService;
using Forum.Web.Controllers.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Web.Controllers.Posts
{
    public class MyPostsController : BaseController
    {
        private readonly IPostService postService;
        private readonly ICategoryService categoryService;

        public MyPostsController(IPostService postService, IUserService userService, ICategoryService categoryService)
            : base(userService)
        {
            this.postService = postService;
            this.categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var myPosts = this.postService.GetAllByUser(CurrentUser.UserId);
            return View(myPosts);
        }

        public IActionResult Create()
        {
            var post = new PostCreateViewModel();
            return this.PostView(post);
        }

        [HttpPost]
        public IActionResult Create(PostCreateViewModel post)
        {

            post.UserId = CurrentUser.UserId;
            post.Categories = this.GetCategories();

            if (!this.ModelState.IsValid)
            {
                return this.View(post);
            }

            this.postService.Create(post);
            return this.RedirectToAction("Index","Posts");
            
        }
        public IActionResult Edit(int id)
        {
            var post = this.postService.GetByIdModel(id);
            return this.PostView(post.ToViewModel());
        }
        [HttpPost]
        public IActionResult Edit (int id, PostCreateViewModel post)
        {
            if (!this.ModelState.IsValid)
            {
                return this.PostView(post);
            }
            try
            {      
                this.postService.Update(id, post);
            }
            catch (EntityNotFoundException)
            {
                return this.View(PostNotFound(id));
            }
            return this.RedirectToAction(nameof(this.Index));
        }
        private IActionResult PostView(PostCreateViewModel postViewModel)
        {
            postViewModel.Categories = this.GetCategories();
            return this.View(postViewModel);
        }

            private SelectList GetCategories()
        {
            var categories = this.categoryService.GetAll();
            return new SelectList(categories,"CategoryId","Name");
        }
        private IActionResult PostNotFound(int id)
        {
            this.Response.StatusCode = StatusCodes.Status404NotFound;
            this.ViewData["error"] = $"Post with id {id} does not exist.";
            return this.View("Error");
        }
    }
}

Forum/Forum.Web/Controllers/Posts/PostsController.cs
using Forum.Models;
using Forum.Services.Contracts;
using Forum.Services.PostService;
using Forum.Web.Controllers.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Web.Controllers
{
    public class PostsController : BaseController
    {
        private readonly IPostService postService;
        private readonly IPostLikeService postLikeService;
        private readonly ICommentLikeService commentLikeService;


        public PostsController(IPostService postService, IUserService userService, IPostLikeService postLikeService, ICommentLikeService commentLikeService)
       : base(userService)
        {
            this.postService = postService;
            this.postLikeService = postLikeService;
            this.commentLikeService = commentLikeService;
        }

        public IActionResult Index()
        {
            var posts = this.postService.GetAllPosts();
            return View(posts);
        }

        public IActionResult CommentsForPost(int id)
        {
            var post = this.postService.GetById(id);
            ViewBag.postId = id;

            return View(post);
        }

        public IActionResult LikesForPost(int id)
        {
            var likeModel = new PostLikeCreateModel
            {
                PostId = id,
                UserId = this.CurrentUser.UserId
            };

            this.postLikeService.Create(likeModel);

            return this.RedirectToAction("Index");
        }

       public IActionResult LikesForComment(int id)
       {
           var likeModel = new CommentLikeCreateModel();
           likeModel.CommentId = id;
           likeModel.UserId = CurrentUser.UserId;
           this.commentLikeService.Create(likeModel);
           return this.RedirectToAction("CommentsForPost", new { id = id });
       }
               
       public IActionResult AddCommentForPost(int postId, string description)
       {
           var commentModel = new CommentCreateModel();
           commentModel.PostId = postId;
           commentModel.UserId = CurrentUser.UserId;
           commentModel.Description = description;
           return this.RedirectToAction("CommentsForPost", new { id = postId });
       }
    }
}

Forum/Forum.Web/Views/Posts/CommentsForPost.cshtml
@{
    ViewData["Title"] = "Post";
}

@model Forum.Models.PostPresentModel
<div class="card text-white bg-primary mb-3" style="max-width: 30rem;">
    <div class="card-header"><h4>@ViewData["Title"]</h4></div>
    <form asp-action="Index" asp-controller="Comments">
        <div class="card-body">
            <h4 class="card-title">@ViewData["Title"] : @Model.Title</h4>
            <label class="form-label mt-4">Created by: </label>
            <label class="form-label mt-4">@Model.CreatedBy</label>
            <br />
            <label class="form-label mt-4">Category: </label>
            <label class="form-label mt-4">@Model.CategoryName</label>
            <br />
            <label class="form-label mt-4">Content: </label>
            <label class="form-label mt-4">@Model.Content</label>
            <br />
            <a style="float: right; margin-bottom: 5px;" asp-route-postId="@Model.PostId" asp-controller="Comments" asp-action="Index" class="btn btn-danger">Add comment</a>
        </div>
    </form>
</div>

@foreach (var comment in Model.Comments)
{
    <div>

    </div>
    <div class="row">
        <div class="col-lg-8">
            <div class="card border-primary mb-3" style="max-width: 80rem;">
                <div class="card-header">@comment.CommentedBy</div>
                <div class="card-body">
                    <p class="card-text">@comment.Description</p>
                    <div style="float: right; position: relative; display: inline-flex;">
                        <div class="row">
                            <div class="col-lg-5">
                                <p style="margin:auto;">@comment.LikesCount</p>
                            </div>
                            <div class="col-lg-5">
                                <p><a asp-controller="Posts" asp-action="LikesForComment" asp-route-id="@comment.CommentId" asp-route-postId="@Model.PostId" class="badge rounded-pill bg-info"> Like </a></p>
                            </div>
                            <div class="col-lg-2"></div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
 }

Forum/Forum.Web/Views/Posts/Index.cshtml
@{
}
@model IEnumerable<Forum.Models.PostPresentModel>

<table class="table table-hover">

  

    @foreach (var post in @Model)
    {
    <div align="center">
        <div class="card border-info mb-3" style="max-width: 50rem;">
            <div class="card-header">@post.CategoryName</div>
            <div class="card-body">
                <h4 class="card-title">@post.Title</h4>
                <div class="row">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-10">
                        <p class="card-text" align="left">@post.Content</p>
                    </div>
                    <div class="col-lg-1"></div>
                </div>
                <div class="row">&nbsp;</div>
                <div class="row">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-1">
                        <p> <img src="~/img/imgbin-like-L0Gm29uWtN96Gdk5rxXEbap65_t.jpg" width="20" height="20" /> @post.LikesCount</p>
                    </div>
                    <div class="col-lg-1">
                        <a asp-action="LikesForPost" asp-route-id="@post.PostId" class="badge rounded-pill bg-info" align="left">like</a>
                    </div>
                    <div class="col-lg-6"></div>

                    <div class="col-lg-1">
                        <p><img src="~/img/comment-icon.jpg" width="20" height="20" /> @post.CommentsCount</p>
                    </div>
                    <div class="col-lg-1">
                        <a asp-action="CommentsForPost" asp-route-id="@post.PostId" class="badge bg-warning" align="rignt"> comment </a>
                    </div>
                    <div class="col-lg-1"></div>
                </div>
            </div>
        </div>
    </div>
    }
</table>
}